<div id="pwads">

<!-- Project Wonderful Ad Box Code -->
<div id="pw_adbox_70223_3_0"></div>
<script type="text/javascript"></script>
<noscript><map name="admap70223" id="admap70223"><area href="http://www.projectwonderful.com/out_nojs.php?r=0&c=0&id=70223&type=3" shape="rect" coords="0,0,160,600" title="" alt="" target="_blank" /></map>
<table cellpadding="0" cellspacing="0" style="width:160px;border-style:none;background-color:#ffffff;"><tr><td><img src="http://www.projectwonderful.com/nojs.php?id=70223&type=3" style="width:160px;height:600px;border-style:none;" usemap="#admap70223" alt="" /></td></tr><tr><td style="background-color:#ffffff;" colspan="1"><center><a style="font-size:10px;color:#0000ff;text-decoration:none;line-height:1.2;font-weight:bold;font-family:Tahoma, verdana,arial,helvetica,sans-serif;text-transform: none;letter-spacing:normal;text-shadow:none;white-space:normal;word-spacing:normal;" href="http://www.projectwonderful.com/advertisehere.php?id=70223&type=3" target="_blank">Ads by Project Wonderful!  Your ad here, right now: $0</a></center></td></tr></table>
</noscript>
<!-- End Project Wonderful Ad Box Code -->

<!-- Project Wonderful Ad Box Code -->
<div id="pw_adbox_1715_1_0"></div>
<script type="text/javascript"></script>
<noscript><map name="admap1715" id="admap1715"><area href="http://www.projectwonderful.com/out_nojs.php?r=0&c=0&id=1715&type=1" shape="rect" coords="0,0,468,60" title="" alt="" target="_top" /></map>
<table cellpadding="0" cellspacing="0" style="width:468px;border-style:none;background-color:;"><tr><td><img src="http://www.projectwonderful.com/nojs.php?id=1715&type=1" style="width:468px;height:60px;border-style:none;" usemap="#admap1715" alt="" /></td></tr><tr><td colspan="1"><center><a style="font-size:10px;color:#0000ff;text-decoration:none;line-height:1.2;font-weight:bold;font-family:Tahoma, verdana,arial,helvetica,sans-serif;text-transform: none;letter-spacing:normal;text-shadow:none;white-space:normal;word-spacing:normal;" href="http://www.projectwonderful.com/advertisehere.php?id=1715&type=1&tag=2064" target="_blank">Your ad here, right now: $0</a></center></td></tr></table>
</noscript>
<!-- End Project Wonderful Ad Box Code -->

<img class="analytics" src="a.pl/flrig-site" width=1 height=1>

<div id="about">
<h2>About</h2>

<p>This page simply reformats the Flickr public RSS feed for easy browsing and finding inspiration. All images are &copy; to their original owners; please see their respective user pages for more information.</p>

<p>Unfortunately the Flickr RSS feed does not provide any further license information; if this were present I would gladly include it. If you would like this to change, please contact Flickr support and ask them to support proper license information in the feed.</p>
</div>
